import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";


import Menu from "./menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html lang="vi">
<body className="text-black">
<header className="w-full max-w-[1400px] mx-auto overflow-hidden rounded-lg h-100">
  <img src="/img/bn.webp" alt="Banner" className="w-full h-full object-cover block" />
</header>
<hr />
  
  <nav className="bg-black h-[60px] flex justify-center items-center space-x-5 text-2x1 "> 
    
     <Menu></Menu>
      </nav>
    <main className="min-h-[300]  bg-pink-700"> 
    {children}
     </main>
    
</body>
</html>

  );
}
